import turtle
s = turtle.Screen()
t = turtle.Turtle(shape='turtle')
t2 = turtle.Turtle(shape='turtle')
t3 = turtle.Turtle(shape='turtle')
t4 = turtle.Turtle(shape='turtle')
t2.penup()
t2.goto(0, -25)
t3.penup()
t3.goto(-50, -50)
t4.penup()
t4.goto(50, -25)
t.penup()
t.goto(-300, 0)
t.pendown()
for i in range(8):
    t.setheading(-45)
    t.circle(50, 90)
t.penup()
t.goto(-100, 200)
t.pendown()
t.circle(50)
t.penup()
t.goto(0, -75)